name: norm
description: "Norm: Habit tracker"

publish_to: 'none'

version: 0.3.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.7
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  hive_ce_flutter: ^2.3.3
  home_widget: ^0.8.1
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.6
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  comments_remover: ^1.0.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-Regular.ttf
        - asset: fonts/Figtree-Medium.ttf
        - asset: fonts/Figtree-SemiBold.ttf
        - asset: fonts/Figtree-Bold.ttf
        - asset: fonts/Figtree-ExtraBold.ttf
        - asset: fonts/Figtree-Black.ttf
        - asset: fonts/Figtree-Light.ttf