name: norm
description: "Norm: Habit tracker"

publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.4
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^3.0.1
  hive_ce_flutter: ^2.3.2
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.1
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  provider: ^6.1.5+1
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-Regular.ttf
        - asset: fonts/Figtree-Medium.ttf
        - asset: fonts/Figtree-SemiBold.ttf
        - asset: fonts/Figtree-Bold.ttf
        - asset: fonts/Figtree-ExtraBold.ttf
        - asset: fonts/Figtree-Black.ttf
        - asset: fonts/Figtree-Light.ttf